version: "3"


services:
  aws-s3:
    image: localstack/localstack
    container_name: aws-s3
    ports:
      - "4572:4572"
    environment:
      - SERVICES=s3:4572
  spark-livy:
    image: spark-livy
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8998:8998"
    environment:
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - AWS_S3_ENDPOINT=http://aws-s3:4572

